# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: dynamic-consistency-boundary
name: abrechnung
description: >-
  Verwaltet die Rechnungen.
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
identifiedBy:
  - name: rechnung
    source: command-payload
    field: rechnungId
consults:
  - boundedContext: naturheilpraxis
    event: rechnung-erstellt
    criteria: Die ID ist die gleiche wie im auslösenden Befehl.
  - boundedContext: naturheilpraxis
    event: rechnung-geaendert
    criteria: Die ID ist die gleiche wie im auslösenden Befehl.
  - boundedContext: naturheilpraxis
    event: entwurf-geloescht
    criteria: Die ID ist die gleiche wie im auslösenden Befehl.
  - boundedContext: naturheilpraxis
    event: rechnung-versendet
    criteria: Die ID ist die gleiche wie im auslösenden Befehl.
  - boundedContext: naturheilpraxis
    event: rechnung-bezahlt
    criteria: Die ID ist die gleiche wie im auslösenden Befehl.
  - boundedContext: naturheilpraxis
    event: rechnungszahlung-zurueckgenommen
    criteria: Die ID ist die gleiche wie im auslösenden Befehl.
  - boundedContext: naturheilpraxis
    event: rechnungsversand-zurueckgenommen
    criteria: Die ID ist die gleiche wie im auslösenden Befehl.

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: command
name: rechnung-erstellen
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
  dynamicConsistencyBoundary: abrechnung
data:
  type: object
  properties:
    rechnungId:
      type: string
      format: uuid
    praxiskuerzel:
      type: string
    patientennummer:
      $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=patientennummer
    diagnosetext:
      type: string
    rechnungstext:
      type: string
    leistungen:
      type: array
      minItems: 1
      items:
        type: string
        format: uuid
  required:
    - rechnungId
    - praxiskuerzel
    - patientennummer
    - diagnosetext
    - rechnungstext
    - leistungen
  additionalProperties: false
publishes:
  - rechnung-erstellt
actors:
  - heilpraktiker

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: event
name: rechnung-erstellt
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
data:
  type: object
  properties:
    rechnungId:
      type: string
      format: uuid
    praxiskuerzel:
      type: string
    patientennummer:
      $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=patientennummer
    diagnosetext:
      type: string
    rechnungstext:
      type: string
    leistungen:
      type: array
      minItems: 1
      items:
        type: string
        format: uuid
  required:
    - rechnungId
    - praxiskuerzel
    - patientennummer
    - diagnosetext
    - rechnungstext
    - leistungen
  additionalProperties: false

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: command
name: rechnung-aendern
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
  dynamicConsistencyBoundary: abrechnung
data:
  type: object
  properties:
    rechnungId:
      type: string
      format: uuid
    praxiskuerzel:
      type: string
    diagnosetext:
      type: string
    rechnungstext:
      type: string
    leistungen:
      type: array
      minItems: 1
      items:
        type: string
        format: uuid
  required:
    - rechnungId
    - praxiskuerzel
    - diagnosetext
    - rechnungstext
    - leistungen
  additionalProperties: false
publishes:
  - rechnung-geaendert
actors:
  - heilpraktiker

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: event
name: rechnung-geaendert
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
data:
  type: object
  properties:
    rechnungId:
      type: string
      format: uuid
    praxiskuerzel:
      type: string
    diagnosetext:
      type: string
    rechnungstext:
      type: string
    leistungen:
      type: array
      minItems: 1
      items:
        type: string
        format: uuid
  required:
    - rechnungId
    - praxiskuerzel
    - diagnosetext
    - rechnungstext
    - leistungen
  additionalProperties: false

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: command
name: entwurf-loeschen
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
  dynamicConsistencyBoundary: abrechnung
data:
  type: object
  properties:
    rechnungId:
      type: string
      format: uuid
  required:
    - rechnungId
  additionalProperties: false
publishes:
  - entwurf-geloescht
actors:
  - heilpraktiker

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: event
name: entwurf-geloescht
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
data:
  type: object
  properties:
    rechnungId:
      type: string
      format: uuid
  required:
    - rechnungId
  additionalProperties: false

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: command
name: rechnung-versenden
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
  dynamicConsistencyBoundary: abrechnung
data:
  type: object
  properties:
    rechnungId:
      type: string
      format: uuid
    datum:
      type: string
      format: date
  required:
    - rechnungId
    - datum
  additionalProperties: false
publishes:
  - rechnung-versendet
actors:
  - heilpraktiker
constraints:
  - name: rechnungsnummer-erstellen
    rule: >-
      Im Ereignis `rechnung-versendet` wird die vergebene Rechnungsnummer angegeben. Die neue
      Rechnungsnummer hat das Format `P/JJMMTT[-N]` und besteht aus der Patientennummer `P` und dem
      Rechnungsdatum `JJMMTT`. Gibt es mehr als eine Rechnung für denselben Patienten an einem Tag,
      wird eine fortlaufende Zahl `-N` angehängt, beginnend bei 2. Vergeben sind nur die Nummern
      versendeter und bezahlter Rechnungen; eine durch Zurücknahme des Versands frei gewordene
      Nummer kann wieder vergeben werden. Es wird immer die niedrigste freie Nummer vergeben.

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: event
name: rechnung-versendet
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
data:
  type: object
  properties:
    rechnungId:
      type: string
      format: uuid
    rechnungsnummer:
      $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=rechnungsnummer
    datum:
      type: string
      format: date
  required:
    - rechnungId
    - rechnungsnummer
    - datum
  additionalProperties: false

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: command
name: zahlung-erfassen
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
  dynamicConsistencyBoundary: abrechnung
data:
  type: object
  properties:
    rechnungId:
      type: string
      format: uuid
  required:
    - rechnungId
  additionalProperties: false
publishes:
  - rechnung-bezahlt
actors:
  - heilpraktiker

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: event
name: rechnung-bezahlt
description: Eine Rechnung wurde vom Patienten bezahlt.
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
data:
  type: object
  properties:
    rechnungId:
      type: string
      format: uuid
  required:
    - rechnungId
  additionalProperties: false

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: command
name: rechnung-zurueckstufen
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
  dynamicConsistencyBoundary: abrechnung
data:
  type: object
  properties:
    rechnungId:
      type: string
      format: uuid
  required:
    - rechnungId
  additionalProperties: false
publishes:
  - rechnungszahlung-zurueckgenommen
  - rechnungsversand-zurueckgenommen
actors:
  - heilpraktiker
constraints:
  - name: ereignis-haengt-vom-status-ab
    rule: >-
      Es wird immer genau eines der beiden Ereignisse emittiert: im Status `bezahlt` das Ereignis
      `rechnungszahlung-zurueckgenommen`, im Status `versendet` das Ereignis
      `rechnungsversand-zurueckgenommen`.
  - name: versand-zuruecknehmen-entfernt-nummer
    rule: >-
      Wird der Versand zurückgenommen, verliert die Rechnung Rechnungsnummer und Rechnungsdatum.
      Beide werden beim erneuten Versand neu vergeben.

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: event
name: rechnungszahlung-zurueckgenommen
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
data:
  type: object
  properties:
    rechnungId:
      type: string
      format: uuid
  required:
    - rechnungId
  additionalProperties: false

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: event
name: rechnungsversand-zurueckgenommen
description: >-
  Die Rechnung ist wieder ein Entwurf und hat keine Rechnungsnummer und kein Rechnungsdatum mehr.
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
data:
  type: object
  properties:
    rechnungId:
      type: string
      format: uuid
  required:
    - rechnungId
  additionalProperties: false
