# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: dynamic-consistency-boundary
name: diagnosestellung
description: >-
  Verwaltet die Diagnosen.
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
identifiedBy:
  - name: diagnose
    source: command-payload
    field: diagnoseId
consults:
  - boundedContext: naturheilpraxis
    event: diagnose-gestellt
    criteria: Die ID ist die gleiche wie im auslösenden Befehl.
  - boundedContext: naturheilpraxis
    event: diagnose-geaendert
    criteria: Die ID ist die gleiche wie im auslösenden Befehl.
  - boundedContext: naturheilpraxis
    event: diagnose-geloescht
    criteria: Die ID ist die gleiche wie im auslösenden Befehl.

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: command
name: diagnose-stellen
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
  dynamicConsistencyBoundary: diagnosestellung
data:
  $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/entity=diagnose
  properties:
    diagnoseId:
      type: string
      format: uuid
publishes:
  - diagnose-gestellt
actors:
  - heilpraktiker

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: event
name: diagnose-gestellt
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
data:
  $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/entity=diagnose

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: command
name: diagnose-aendern
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
  dynamicConsistencyBoundary: diagnosestellung
data:
  $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/entity=diagnose
  properties:
    diagnoseId:
      type: string
      format: uuid
publishes:
  - diagnose-geaendert
actors:
  - heilpraktiker

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: event
name: diagnose-geaendert
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
data:
  $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/entity=diagnose

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: command
name: diagnose-loeschen
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
  dynamicConsistencyBoundary: diagnosestellung
data:
  type: object
  properties:
    diagnoseId:
      type: string
      format: uuid
  required:
    - diagnoseId
  additionalProperties: false
publishes:
  - diagnose-geloescht
actors:
  - heilpraktiker

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: event
name: diagnose-geloescht
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
data:
  type: object
  properties:
    diagnoseId:
      type: string
      format: uuid
  required:
    - diagnoseId
  additionalProperties: false
