# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: read-model
name: gebuehrenansicht
description: >-
  Der aktuelle Stand des Gebührenverzeichnisses.
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
paradigm: tabular
projections:
  - boundedContext: naturheilpraxis
    event: gebuehr-angelegt
    rule: Füge die Gebühr hinzu.
  - boundedContext: naturheilpraxis
    event: gebuehr-geaendert
    rule: Aktualisiere die Gebühr.
  - boundedContext: naturheilpraxis
    event: gebuehr-entfernt
    rule: Entferne die Gebühr.
schema:
  type: array
  items:
    $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/entity=gebuehr

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: query
name: gebuehren-ermitteln
description: >-
  Ermittelt die Gebühren des Verzeichnisses.
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
readModel: gebuehrenansicht
paradigm: tabular
result:
  type: array
  items:
    $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/entity=gebuehr
actors:
  - heilpraktiker
constraints:
  - name: nach-ziffer-sortiert
    rule: >-
      Die Gebühren sind aufsteigend nach Ziffer natürlich sortiert. Zahlen in der Ziffer werden
      numerisch verglichen, sodass etwa `3` vor `20.1` steht.
