# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: dynamic-consistency-boundary
name: patientenkartei
description: >-
  Die Patientenaufnahme und die Patientenkartei müssen getrennt voneinander behandelt werden, weil
  bei der Aufnahme die Patientennummer automatisch vergeben wird und in der Kartei bekannt sein
  muss.
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
identifiedBy:
  - name: patient
    source: command-payload
    field: patientennummer
consults:
  - boundedContext: naturheilpraxis
    event: patient-aufgenommen
    criteria: >-
      Die Nummer ist die gleiche wie im auslösenden Befehl oder wie in `partnerVon` oder `kindVon`
      des Befehls.
  - boundedContext: naturheilpraxis
    event: patientendaten-geaendert
    criteria: Die Nummer ist die gleiche wie im auslösenden Befehl.
  - boundedContext: naturheilpraxis
    event: praxis-angelegt
    criteria: >-
      Die Ereignisse der Praxis mit dem Kürzel aus dem Befehl.

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: command
name: patientendaten-aendern
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
  dynamicConsistencyBoundary: patientenkartei
data:
  $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/entity=patient
  properties:
    patientennummer:
      $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=patientennummer
publishes:
  - patientendaten-geaendert
actors:
  - heilpraktiker
constraints:
  - name: praxis-existiert
    rule: >-
      Die Praxis mit dem angegebenen Kürzel muss angelegt sein, sonst wird der Befehl abgelehnt.
  - name: angehoerige-existieren
    rule: >-
      Die Patienten, die in `partnerVon` und `kindVon` angegeben sind, müssen aufgenommen sein,
      sonst wird der Befehl abgelehnt.
  - name: nicht-eigener-partner-oder-kind
    rule: >-
      Ist in `partnerVon` oder `kindVon` die eigene Patientennummer angegeben, wird der Befehl
      abgelehnt.

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: event
name: patientendaten-geaendert
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
data:
  $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/entity=patient
