# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: dynamic-consistency-boundary
name: patientenkartei
description: >-
  Die Patientenaufnahme und die Patientenkartei müssen getrennt voneinander behandelt werden, weil
  bei der Aufnahme die Patientennummer automatisch vergeben wird und in der Kartei bekannt sein
  muss.
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
identifiedBy:
  - name: patient
    source: command-payload
    field: patientennummer
consults:
  - boundedContext: naturheilpraxis
    event: patient-aufgenommen
    criteria: Die Nummer ist die gleiche wie im auslösenden Befehl.
  - boundedContext: naturheilpraxis
    event: patientendaten-geaendert
    criteria: Die Nummer ist die gleiche wie im auslösenden Befehl.

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: command
name: patientendaten-aendern
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
  dynamicConsistencyBoundary: patientenkartei
data:
  type: object
  properties:
    patientennummer:
      $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=patientennummer
    praxiskuerzel:
      type: string
    annahmejahr:
      type: integer
    geburtsdatum:
      type: string
      format: date
    name:
      $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=personenname
    anschrift:
      $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=anschrift
    kontakt:
      $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=kontakt
    beruf:
      type: string
    familienstand:
      type: string
    staatsangehoerigkeit:
      type: string
    notizen:
      type: string
    partnerVon:
      $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=patientennummer
    kindVon:
      $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=patientennummer
    schluesselworte:
      type: array
      items:
        type: string
  required:
    - patientennummer
    - praxiskuerzel
    - annahmejahr
    - name
    - geburtsdatum
  additionalProperties: false
publishes:
  - patientendaten-geaendert
actors:
  - heilpraktiker

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: event
name: patientendaten-geaendert
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
data:
  $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/entity=patient
