# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: read-model
name: patientenansicht
description: >-
  Die aktuelle Liste aller Patienten des Heilpraktikers.
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
paradigm: key-value
projections:
  - boundedContext: naturheilpraxis
    event: patient-aufgenommen
    rule: Fügt einen Patienten hinzu.
  - boundedContext: naturheilpraxis
    event: patientendaten-geaendert
    rule: Aktualisiert die Stammdaten des Patienten.
schema:
  type: array
  items:
    $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/entity=patient

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: query
name: patienten-ermitteln
description: >-
  Ermittelt Patienten, wahlweise eingeschränkt auf einen Suchbegriff.
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
readModel: patientenansicht
paradigm: tabular
parameters:
  type: object
  properties:
    suchbegriff:
      type: string
  additionalProperties: false
result:
  type: array
  items:
    type: object
    properties:
      patientennummer:
        $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=patientennummer
      praxiskuerzel:
        type: string
      annahmejahr:
        type: integer
      geburtsdatum:
        type: string
        format: date
      anrede:
        type: string
      titel:
        type: string
      vorname:
        type: string
      nachname:
        type: string
      strasse:
        type: string
      zusatz:
        type: string
      postleitzahl:
        type: string
      ort:
        type: string
      staat:
        type: string
      telefon:
        type: string
      mobiltelefon:
        type: string
      email:
        type: string
        format: email
      website:
        type: string
        format: uri
      beruf:
        type: string
      familienstand:
        type: string
      staatsangehoerigkeit:
        type: string
      notizen:
        type: string
      partnerVon:
        $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=patientennummer
      partnerVonName:
        type: string
      kindVon:
        $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=patientennummer
      kindVonName:
        type: string
      schluesselworte:
        type: array
        items:
          type: string
    required:
      - patientennummer
      - praxiskuerzel
      - annahmejahr
      - vorname
      - nachname
      - strasse
      - postleitzahl
      - ort
      - geburtsdatum
    additionalProperties: false
actors:
  - heilpraktiker
constraints:
  - name: nach-nummer-sortiert
    rule: >-
      Die Patienten sind absteigend nach Patientennummer sortiert. Das bedeutet, dass die neuesten
      Patienten zuerst erscheinen.
  - name: suchbegriff-trifft
    rule: >-
      Ist ein Suchbegriff angegeben, bleiben nur die Patienten übrig, bei denen der Suchbegriff in
      einem beliebigen Feld vorkommt. Besteht der Suchbegriff aus mehreren Wörtern, müssen alle
      Wörter vorkommen, aber nicht zwingend im gleichen Feld. Enthält ein Suchwort Leerzeichen, muss
      es in Anführungszeichen gesetzt werden. Groß- und Kleinschreibung spielen keine Rolle.

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: query
name: patient-ermitteln
description: Ermittelt die Patientenkarteikarte eines Patienten anhand seiner Patientennummer.
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
readModel: patientenansicht
paradigm: document
parameters:
  type: object
  properties:
    patientennummer:
      $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=patientennummer
  required:
    - patientennummer
  additionalProperties: false
result:
  patientennummer:
    $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=patientennummer
  praxiskuerzel:
    type: string
  annahmejahr:
    type: integer
  geburtsdatum:
    type: string
    format: date
  name:
    $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=personenname
  anschrift:
    $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=anschrift
  kontakt:
    $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=kontakt
  beruf:
    type: string
  familienstand:
    type: string
  staatsangehoerigkeit:
    type: string
  notizen:
    type: string
  partnerVon:
    $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=patientennummer
  partnerVonName:
    type: string
  kindVon:
    $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=patientennummer
  kindVonName:
    type: string
  schluesselworte:
    type: array
    items:
      type: string
  required:
    - patientennummer
    - praxiskuerzel
    - annahmejahr
    - name
    - geburtsdatum
  additionalProperties: false
actors:
  - heilpraktiker
constraints:
  - name: nach-patientennummer-eingrenzen
    rule: Es wird nur der Patient mit der angegebenen Patientennummer zurückgegeben.
