# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: dynamic-consistency-boundary
name: patientenaufnahme
description: >-
  Die Patientennummer muss eindeutig sein und fortlaufend vergeben werden. Dafür müssen alle
  Ereignisse über aufgenommene Patienten betrachtet werden, um die höchste bisher vergebene Nummer
  zu kennen. Die Patientenaufnahme und die Patientenkartei müssen getrennt voneinander behandelt
  werden, weil bei der Aufnahme die Patientennummer automatisch vergeben wird und in der Kartei
  bekannt sein muss.
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
identifiedBy:
  - name: patientenaufnahme
    source: static
    value: patientennummer
consults:
  - boundedContext: naturheilpraxis
    event: patient-aufgenommen
    criteria: Alle Ereignisse, unabhängig von der Patientennummer.
  - boundedContext: naturheilpraxis
    event: praxis-angelegt
    criteria: >-
      Die Ereignisse der Praxis mit dem Kürzel aus dem Befehl.
invariants:
  - name: praxis-existiert
    rule: >-
      Die Praxis, in der ein Patient aufgenommen wird, muss angelegt sein.
  - name: angehoerige-existieren
    rule: >-
      Die Patienten, die in `partnerVon` und `kindVon` angegeben sind, müssen aufgenommen sein.

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: command
name: patient-aufnehmen
description: >-
  Im Befehl fehlt die Patientennummer, da diese automatisch vergeben wird und im veröffentlichten
  Ereignis enthalten ist.
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
  dynamicConsistencyBoundary: patientenaufnahme
data:
  type: object
  properties:
    praxiskuerzel:
      type: string
    aufnahmejahr:
      type: integer
    geburtsdatum:
      type: string
      format: date
    name:
      $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=personenname
    anschrift:
      $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=anschrift
    kontakt:
      $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=kontakt
    beruf:
      type: string
    familienstand:
      type: string
    staatsangehoerigkeit:
      type: string
    notizen:
      type: string
    partnerVon:
      $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=patientennummer
    kindVon:
      $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/value-object=patientennummer
    schluesselworte:
      type: array
      items:
        type: string
  required:
    - praxiskuerzel
    - aufnahmejahr
    - name
    - geburtsdatum
  additionalProperties: false
publishes:
  - patient-aufgenommen
actors:
  - heilpraktiker
constraints:
  - name: patientennummer-fortlaufend-ab-eins
    rule: >-
      Im Ereignis `patient-aufgenommen` wird die vergebene Patientennummer angegeben. Die neue
      Patientennummer ist um eins größer als die höchste bisher vergebene Nummer. Der erste Patient
      überhaupt erhält die Nummer 1.

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: event
name: patient-aufgenommen
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
data:
  $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/entity=patient
