# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: dynamic-consistency-boundary
name: praxisverwaltung
description: >-
  Das Praxiskürzel muss eindeutig sein. Dafür reicht es, alle Ereignisse mit dem gleichen
  Praxiskürzel zu betrachten.
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
identifiedBy:
  - name: praxis
    source: command-payload
    field: praxiskuerzel
consults:
  - boundedContext: naturheilpraxis
    event: praxis-angelegt
    criteria: Das Kürzel ist das gleiche wie im auslösenden Befehl.
  - boundedContext: naturheilpraxis
    event: praxisdaten-geaendert
    criteria: Das Kürzel ist das gleiche wie im auslösenden Befehl.

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: command
name: praxis-anlegen
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
  dynamicConsistencyBoundary: praxisverwaltung
data:
  $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/entity=praxis
  properties:
    praxiskuerzel:
      type: string
publishes:
  - praxis-angelegt
actors:
  - heilpraktiker

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: event
name: praxis-angelegt
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
data:
  $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/entity=praxis

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: command
name: praxisdaten-aendern
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
  dynamicConsistencyBoundary: praxisverwaltung
data:
  $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/entity=praxis
  properties:
    praxiskuerzel:
      type: string
publishes:
  - praxisdaten-geaendert
actors:
  - heilpraktiker

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: event
name: praxisdaten-geaendert
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
data:
  $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/entity=praxis
