# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: read-model
name: praxenansicht
description: >-
  Die aktuelle Liste der Praxen des Heilpraktikers.
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
paradigm: key-value
projections:
  - boundedContext: naturheilpraxis
    event: praxis-angelegt
    rule: Füge eine Praxis hinzu.
  - boundedContext: naturheilpraxis
    event: praxisdaten-geaendert
    rule: Aktualisiere die Stammdaten der Praxis.
schema:
  type: array
  items:
    $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/entity=praxis

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: query
name: praxen-ermitteln
description: Ermittelt alle Praxen des Heilpraktikers.
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
readModel: praxenansicht
paradigm: tabular
result:
  type: array
  items:
    type: object
    properties:
      praxiskuerzel:
        type: string
      name:
        type: string
      strasse:
        type: string
      zusatz:
        type: string
      postleitzahl:
        type: string
      ort:
        type: string
      staat:
        type: string
      telefon:
        type: string
      mobiltelefon:
        type: string
      email:
        type: string
        format: email
      website:
        type: string
        format: uri
      rechnungstext:
        type: string
    required:
      - praxiskuerzel
      - name
      - strasse
      - postleitzahl
      - ort
    additionalProperties: false
actors:
  - heilpraktiker
constraints:
  - name: nach-kuerzel-sortiert
    rule: Die Praxen sind alphanumerisch aufsteigend nach Praxiskürzel sortiert.

---
# $schema: ../schemas/core/v1.yaml
apiVersion: schema.esdm.io/core/v1
kind: query
name: praxis-ermitteln
description: Ermittelt eine Praxis.
scope:
  domain: naturheilpraxis
  boundedContext: naturheilpraxis
readModel: praxenansicht
paradigm: document
parameters:
  type: object
  properties:
    praxiskuerzel:
      type: string
  required:
    - praxiskuerzel
  additionalProperties: false
result:
  $ref: esdm:domain=naturheilpraxis/bounded-context=naturheilpraxis/entity=praxis
actors:
  - heilpraktiker
constraints:
  - name: nach-kuerzel-eingrenzen
    rule: Es wird nur die Praxis mit dem angegebenen Kürzel zurückgegeben.
