@startuml
Aufnahme: new
Verarbeiten: working
Anzeigen: view
Bearbeiten: edit

[*] --> Aufnahme

Aufnahme --> Aufnahme: Aktualisiert (updated)
Aufnahme --> Aufnahme: Abbrechen (cancelled)
Aufnahme --> Verarbeiten: Aufnehmen (submit)
Aufnahme --> Anzeigen: Gefunden (found)

Verarbeiten -> Anzeigen: Fertiggestellt (done)

Anzeigen --> Bearbeiten: Bearbeiten (submit)

Bearbeiten --> Bearbeiten: Aktualisiert (updated)
Bearbeiten --> Anzeigen: Abbrechen (cancelled)
Bearbeiten --> Verarbeiten: Speichern (submit)
@enduml
